#!/bin/bash

set -e

echo "=============================================="
echo "🚀 Tekton SLSA Demo - Supply Chain Security in Action"
echo "=============================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Function to check if script exists and run it
run_script() {
    local script_path="$1"
    local description="$2"
    
    if [[ -f "$script_path" ]]; then
        echo ""
        print_info "Running: $description"
        echo "----------------------------------------"
        if "$script_path"; then
            print_status "$description completed successfully"
        else
            print_error "$description failed!"
            exit 1
        fi
    else
        print_error "Script not found: $script_path"
        exit 1
    fi
}

# Function to run interactive demo
run_interactive_demo() {
    echo ""
    echo "🎯 Running Interactive SLSA Compliance Demo"
    echo "============================================"
    
    # Show SLSA Level 2 compliance
    print_info "Demonstrating SLSA Level 2 Compliance"
    echo ""
    
    # Create a real build pipeline
    cat << EOF | kubectl apply -f -
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: slsa-demo-pipeline
  namespace: default
  labels:
    slsa-demo: "true"
spec:
  params:
  - name: IMAGE_NAME
    description: Name of the application image
    default: "tekton-slsa-demo/app"
  - name: IMAGE_TAG
    description: Tag for the application image
    default: "latest"
  - name: SOURCE_URL
    description: Source repository URL
    default: "https://github.com/waveywaves/tekton-slsa-demo"
  results:
  - name: IMAGE_URL
    description: URL of the built image
    value: \$(tasks.build-app.results.IMAGE_URL)
  - name: IMAGE_DIGEST
    description: Digest of the built image
    value: \$(tasks.build-app.results.IMAGE_DIGEST)
  tasks:
  - name: source-scan
    taskSpec:
      steps:
      - name: scan
        image: alpine:3.18
        script: |
          #!/bin/sh
          set -ex
          echo "🔍 Scanning source code for vulnerabilities..."
          echo "Source URL: \$(params.SOURCE_URL)"
          sleep 2
          echo "✅ Source scan completed - no critical issues found"
      params:
      - name: SOURCE_URL
    params:
    - name: SOURCE_URL
      value: \$(params.SOURCE_URL)
  - name: build-app
    runAfter: ["source-scan"]
    taskRef:
      name: enhanced-build-sign
    params:
    - name: IMAGE_NAME
      value: \$(params.IMAGE_NAME)
    - name: IMAGE_TAG
      value: \$(params.IMAGE_TAG)
  - name: security-verify
    runAfter: ["build-app"]
    taskSpec:
      params:
      - name: IMAGE_URL
      steps:
      - name: verify
        image: alpine:3.18
        script: |
          #!/bin/sh
          set -ex
          echo "🛡️  Verifying security compliance..."
          echo "Image: \$(params.IMAGE_URL)"
          sleep 2
          echo "✅ Security verification passed"
    params:
    - name: IMAGE_URL
      value: \$(tasks.build-app.results.IMAGE_URL)
EOF

    print_status "SLSA Demo Pipeline created"
    
    # Run the pipeline
    print_info "Executing SLSA-compliant pipeline..."
    
    cat << EOF | kubectl apply -f -
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: slsa-demo-run-$(date +%s)
  namespace: default
  labels:
    slsa-demo: "true"
spec:
  pipelineRef:
    name: slsa-demo-pipeline
  params:
  - name: IMAGE_NAME
    value: "tekton-slsa-demo/final-app"
  - name: IMAGE_TAG
    value: "v1.0.0-demo"
  - name: SOURCE_URL
    value: "https://github.com/waveywaves/tekton-slsa-demo"
EOF

    # Get the PipelineRun name
    PIPELINE_RUN=$(kubectl get pipelineruns -l slsa-demo=true -o name | tail -1 | cut -d'/' -f2)
    
    print_info "Waiting for PipelineRun $PIPELINE_RUN to complete..."
    kubectl wait --for=condition=succeeded pipelinerun/$PIPELINE_RUN --timeout=300s
    
    print_status "SLSA Demo Pipeline completed successfully!"
    
    # Show the results
    echo ""
    print_info "Demo Results Summary"
    echo "===================="
    
    # Show pipeline results
    echo "📋 Pipeline Results:"
    kubectl get pipelinerun $PIPELINE_RUN -o yaml | grep -A 10 "results:" || echo "No results found"
    
    # Show attestations generated by Chains
    echo ""
    echo "🔐 Tekton Chains Attestations:"
    kubectl get pipelinerun $PIPELINE_RUN -o jsonpath='{.metadata.annotations.chains\.tekton\.dev/signed}' && echo " - Pipeline signed" || echo " - Pipeline signing pending"
    
    # Show all TaskRuns from this pipeline
    echo ""
    echo "📝 TaskRuns Generated:"
    kubectl get taskruns -l tekton.dev/pipelineRun=$PIPELINE_RUN -o custom-columns="NAME:.metadata.name,STATUS:.status.conditions[0].reason,SIGNED:.metadata.annotations.chains\.tekton\.dev/signed"
    
    # Show Chains logs
    echo ""
    echo "🔗 Recent Chains Activity:"
    kubectl logs -n tekton-chains -l app=tekton-chains-controller --tail=5 | grep -E "(payload|sign|Sign)" || echo "No recent signing activity in logs"
}

# Function to show verification commands
show_verification_commands() {
    echo ""
    echo "🔍 SLSA Verification Commands"
    echo "============================="
    
    cat << 'EOF'
# Verify TaskRun signatures
kubectl get taskruns -l slsa-demo=true -o custom-columns="NAME:.metadata.name,SIGNED:.metadata.annotations.chains\.tekton\.dev/signed"

# Check attestation format (SLSA v1.0)
kubectl get configmap chains-config -n tekton-chains -o jsonpath='{.data.artifacts\.taskrun\.format}'

# View detailed attestation information
kubectl logs -n tekton-chains -l app=tekton-chains-controller | grep "Created payload"

# Show transparency log integration
kubectl get configmap chains-config -n tekton-chains -o jsonpath='{.data.transparency\.enabled}'

# List all signed TaskRuns and PipelineRuns
kubectl get taskruns,pipelineruns -A -o jsonpath='{range .items[?(@.metadata.annotations.chains\.tekton\.dev/signed=="true")]}{.kind}/{.metadata.name}{"\n"}{end}'
EOF
}

# Function to show SLSA compliance status
show_slsa_compliance() {
    echo ""
    echo "📊 SLSA Compliance Status"
    echo "========================="
    
    # Check SLSA Level 1
    print_info "SLSA Level 1 - Basic Security Practices"
    echo "  ✅ Scripted build process (Tekton Pipelines)"
    echo "  ✅ Version-controlled pipeline definitions"
    echo "  ✅ Automated provenance generation"
    
    # Check SLSA Level 2
    print_info "SLSA Level 2 - Source Integrity & Authenticated Provenance"
    echo "  ✅ Hosted build service (Kubernetes/Tekton)"
    echo "  ✅ Cryptographically signed provenance (Tekton Chains)"
    echo "  ✅ Tamper-resistant build records"
    
    # Check SLSA Level 3 status
    print_info "SLSA Level 3 - Auditable Build Pipelines (Partial)"
    echo "  ✅ Isolated build environments (Kubernetes containers)"
    echo "  ⚠️  Non-falsifiable provenance (needs SPIFFE/SPIRE)"
    echo "  ⚠️  Trusted Resources (basic implementation available)"
    
    # Check SLSA Level 4 status  
    print_info "SLSA Level 4 - Reproducible Builds (Experimental)"
    echo "  ⚠️  Hermetic builds (experimental Hermekton feature)"
    echo "  📋 Two-person review (organizational policy)"
    
    echo ""
    print_status "Current Implementation: SLSA Level 2 Compliant"
    print_warning "Level 3-4 features available as experimental/partial implementations"
}

# Function to clean up demo resources
cleanup_demo() {
    echo ""
    print_info "Cleaning up demo resources..."
    
    kubectl delete pipelineruns -l slsa-demo=true --ignore-not-found
    kubectl delete taskruns -l slsa-demo=true --ignore-not-found
    kubectl delete pipelines -l slsa-demo=true --ignore-not-found
    
    print_status "Demo cleanup completed"
}

# Main demo flow
main() {
    echo "Welcome to the Tekton SLSA Demo!"
    echo "Let's explore supply chain security with real working examples."
    echo ""
    
    # Check prerequisites
    print_info "Checking demo prerequisites..."
    
    if ! kubectl get namespace tekton-pipelines >/dev/null 2>&1; then
        print_error "Tekton Pipelines not found. Please run installation scripts first."
        exit 1
    fi
    
    if ! kubectl get namespace tekton-chains >/dev/null 2>&1; then
        print_error "Tekton Chains not found. Please run installation scripts first."
        exit 1
    fi
    
    if ! kubectl get task enhanced-build-sign >/dev/null 2>&1; then
        print_error "Enhanced build task not found. Please run 04b-configure-key-signing.sh first."
        exit 1
    fi
    
    print_status "All prerequisites satisfied"
    
    # Show current environment
    echo ""
    print_info "Demo Environment Status"
    echo "======================="
    echo "Tekton Pipelines: $(kubectl get pods -n tekton-pipelines | grep Running | wc -l) pods running"
    echo "Tekton Chains: $(kubectl get pods -n tekton-chains | grep Running | wc -l) pods running"
    echo "Kubernetes Cluster: $(kubectl config current-context)"
    
    # Ask user what they want to do
    echo ""
    echo "Demo Options:"
    echo "1) Run full interactive demo"
    echo "2) Show SLSA compliance status only"
    echo "3) Show verification commands only"
    echo "4) Clean up demo resources"
    echo "5) Exit"
    echo ""
    
    read -p "Choose an option (1-5): " choice
    
    case $choice in
        1)
            run_interactive_demo
            show_slsa_compliance
            show_verification_commands
            ;;
        2)
            show_slsa_compliance
            ;;
        3)
            show_verification_commands
            ;;
        4)
            cleanup_demo
            ;;
        5)
            echo "Demo completed. Thank you!"
            exit 0
            ;;
        *)
            print_warning "Invalid option selected. Running full demo..."
            run_interactive_demo
            show_slsa_compliance
            show_verification_commands
            ;;
    esac
    
    echo ""
    print_status "Tekton SLSA Demo completed successfully!"
    echo ""
    echo "🎉 Thank you for exploring Tekton's SLSA compliance features!"
    echo "For more information, visit: https://tekton.dev/ and https://slsa.dev/"
}

# Handle script arguments
case "${1:-}" in
    --interactive)
        run_interactive_demo
        ;;
    --status)
        show_slsa_compliance
        ;;
    --verify)
        show_verification_commands
        ;;
    --cleanup)
        cleanup_demo
        ;;
    --help)
        echo "Tekton SLSA Demo Usage:"
        echo "  ./run-demo.sh              - Interactive demo menu"
        echo "  ./run-demo.sh --interactive - Run full demo pipeline"
        echo "  ./run-demo.sh --status      - Show SLSA compliance status"
        echo "  ./run-demo.sh --verify      - Show verification commands"
        echo "  ./run-demo.sh --cleanup     - Clean up demo resources"
        echo "  ./run-demo.sh --help        - Show this help message"
        ;;
    *)
        main "$@"
        ;;
esac